CREATE TABLE IF NOT EXISTS p_user_field (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    ENTITY_ID BIGINT NOT NULL,
    FIELD_NAME VARCHAR(70) NOT NULL,
    USER_TYPE_ID VARCHAR(70) NOT NULL,
    XML_ID VARCHAR(255) NULL,
    SORT INT NULL,
    MULTIPLE BOOLEAN NOT NULL DEFAULT '0',
    MANDATORY BOOLEAN NOT NULL DEFAULT '0',
    SHOW_FILTER BOOLEAN NOT NULL DEFAULT '0',
    SHOW_IN_LIST BOOLEAN NOT NULL DEFAULT '0',
    EDIT_IN_LIST BOOLEAN NOT NULL DEFAULT '0',
    IS_SEARCHABLE BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS p_user_field_enum (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_FIELD_ID BIGINT NOT NULL,
    VALUE VARCHAR(255) NULL,
    SORT INT NULL,
    XML_ID VARCHAR(255) NULL,
    FOREIGN KEY (USER_FIELD_ID) REFERENCES p_user_field(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS p_user (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LOGIN BIGINT NOT NULL,
    EMAIL BIGINT NOT NULL,
    PASSWORD BIGINT NOT NULL,
    DATE_REGISTER BIGINT NOT NULL,
    LAST_LOGIN BIGINT NOT NULL,
    NAME BIGINT NOT NULL,
    LAST_NAME BIGINT NOT NULL,
    PERSONAL_GENDER CHAR(1) NOT NULL,
    PERSONAL_PHOTO INT NULL
);

CREATE TABLE IF NOT EXISTS p_option (
    MODULE VARCHAR(50) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    VALUE MEDIUMTEXT NULL,
    DESCRIPTION VARCHAR(255) NULL,
    PRIMARY KEY (`MODULE`),
    UNIQUE (`NAME`)
);
