CREATE TABLE `landing_rate`(
    `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `TITLE` VARCHAR(255) NOT NULL,
    `RATE` DOUBLE(8, 2) NOT NULL
);
CREATE TABLE `contact`(
    `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NAME` VARCHAR(255) NOT NULL,
    `LAST_NAME` VARCHAR(255) NOT NULL,
    `GENDER` VARCHAR(255) NOT NULL,
    `SOURCE_ID` VARCHAR(255) NOT NULL,
    `PHONE` INT NOT NULL,
    `EMAIL` VARCHAR(255) NOT NULL
);
CREATE TABLE `crm_deal`(
    `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `TITLE` VARCHAR(255) NOT NULL,
    `STAGE` VARCHAR(255) NOT NULL,
    `CONTANT_ID` INT NULL,
    `COMPANY_ID` INT NULL,
    `RESPONSIBLE_ID` INT NOT NULL,
    `SOURCE_ID` VARCHAR(255) NOT NULL,
    `COMMENT` TEXT NULL,
    `DATE_CLOSED` DATE NOT NULL,
    `LANDING_DATE_ID` INT NOT NULL,
    `RESULT` TINYINT(1) NULL
);
CREATE TABLE `company`(
    `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NAME` VARCHAR(255) NOT NULL,
    `FUL_NAME` VARCHAR(255) NOT NULL,
    `ADDRESS` VARCHAR(255) NOT NULL,
    `INN` INT NOT NULL,
    `KPP` INT NOT NULL,
    `INDUSTRY` VARCHAR(255) NOT NULL,
    `PHONE` INT NOT NULL,
    `EMAIL` BIGINT NOT NULL,
    `REVENUE` INT NOT NULL
);
CREATE TABLE `users`(
    `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NAME` VARCHAR(255) NOT NULL,
    `LAST_NAME` VARCHAR(255) NOT NULL,
    `EMAIL` VARCHAR(255) NOT NULL,
    `PASSWORD` VARCHAR(255) NOT NULL
);
CREATE TABLE `statement`(
    `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `CREATED_BY` INT NOT NULL,
    `COUNT_MONTH` INT NOT NULL,
    `COUNT_CONTACT` INT NOT NULL,
    `COUNT_COMPANY` INT NOT NULL,
    `MONEY_TURNOVER` BIGINT NOT NULL,
    `COMMENT` TEXT NULL
);
ALTER TABLE
    `crm_deal` ADD CONSTRAINT `crm_deal_responsible_id_foreign` FOREIGN KEY(`RESPONSIBLE_ID`) REFERENCES `users`(`ID`);
ALTER TABLE
    `users` ADD CONSTRAINT `users_id_foreign` FOREIGN KEY(`ID`) REFERENCES `statement`(`ID`);
ALTER TABLE
    `crm_deal` ADD CONSTRAINT `crm_deal_company_id_foreign` FOREIGN KEY(`COMPANY_ID`) REFERENCES `company`(`ID`);
ALTER TABLE
    `crm_deal` ADD CONSTRAINT `crm_deal_contant_id_foreign` FOREIGN KEY(`CONTANT_ID`) REFERENCES `contact`(`ID`);
ALTER TABLE
    `crm_deal` ADD CONSTRAINT `crm_deal_landing_date_id_foreign` FOREIGN KEY(`LANDING_DATE_ID`) REFERENCES `landing_rate`(`ID`);