# Generated by Django 4.2.20 on 2025-05-22 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('module', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'p_option',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserField',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='TITLE', max_length=255)),
                ('entity_id', models.CharField(db_column='ENTITY_ID', max_length=70)),
                ('field_name', models.CharField(db_column='FIELD_NAME', max_length=70)),
                ('user_type_id', models.CharField(db_column='USER_TYPE_ID', max_length=70)),
                ('xml_id', models.CharField(blank=True, db_column='XML_ID', max_length=255, null=True)),
                ('sort', models.IntegerField(blank=True, db_column='SORT', null=True)),
                ('multiple', models.IntegerField(db_column='MULTIPLE')),
                ('mandatory', models.IntegerField(db_column='MANDATORY')),
                ('show_filter', models.IntegerField(db_column='SHOW_FILTER')),
                ('show_in_list', models.IntegerField(db_column='SHOW_IN_LIST')),
                ('edit_in_list', models.IntegerField(db_column='EDIT_IN_LIST')),
                ('is_searchable', models.IntegerField(db_column='IS_SEARCHABLE')),
            ],
            options={
                'db_table': 'p_user_field',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserFieldEnum',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('sort', models.IntegerField(blank=True, null=True)),
                ('xml_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'p_user_field_enum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('login', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('date_register', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('personal_gender', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, null=True)),
                ('personal_photo', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'p_user',
            },
        ),
    ]
