CREATE TABLE IF NOT EXISTS `p_crm_deal` (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    CREATED_BY_ID BIGINT NOT NULL,
    MODIFY_BY_ID BIGINT NULL,
    ASSIGNED_BY_ID BIGINT NOT NULL,
    LEAD_ID BIGINT NULL,
    COMPANY_ID BIGINT NULL,
    CONTACT_ID BIGINT NULL,
    STAGE_ID VARCHAR(255) NOT NULL,
    IS_NEW BOOLEAN NOT NULL DEFAULT '1',
    CLOSED BOOLEAN NOT NULL DEFAULT '0',
    TYPE_ID BIGINT NOT NULL,
    OPPORTUNITY VARCHAR(255) NULL,
    DATE_CREATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATE_MODIFY DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS `p_utm_crm_deal` (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DEAL_ID BIGINT NOT NULL,
    FIELD_ID BIGINT NOT NULL,
    VALUE VARCHAR(255) NULL,
    VALUE_INT BIGINT NULL,
    VALUE_DOUBLE DOUBLE NULL,
    VALUE_DATETIME DATETIME NULL,
    FOREIGN KEY (DEAL_ID) REFERENCES p_crm_deal(ID) ON DELETE CASCADE,
    FOREIGN KEY (FIELD_ID) REFERENCES p_user_field(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `p_crm_contact` (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    SECOND_NAME VARCHAR(255) NOT NULL,
    CREATED_BY_ID BIGINT NOT NULL,
    BIRTHDATE DATE NULL DEFAULT (CURRENT_DATE),
    PHOTO BIGINT NULL,
    MODIFY_BY_ID BIGINT NULL,
    ASSIGNED_BY_ID BIGINT NULL,
    COMPANY_ID BIGINT NULL,
    SOURCE_ID BIGINT NULL,
    LEAD_ID BIGINT NULL,
    DATE_CREATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATE_MODIFY DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `p_utm_crm_contact` (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CONTACT_ID BIGINT NOT NULL,
    FIELD_ID BIGINT NOT NULL,
    VALUE VARCHAR(255) NULL,
    VALUE_INT BIGINT NULL,
    VALUE_DOUBLE DOUBLE NULL,
    VALUE_DATETIME DATETIME NULL,
    FOREIGN KEY (CONTACT_ID) REFERENCES p_crm_contact(ID) ON DELETE CASCADE,
    FOREIGN KEY (FIELD_ID) REFERENCES p_user_field(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `p_crm_status` (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ENTITY_ID VARCHAR(255) NOT NULL,
    STATUS_ID VARCHAR(255) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    COLOR VARCHAR(255) NOT NULL,
    SYSTEM_STATUS BOOLEAN NOT NULL,
    SEMANTICS CHAR(1) NULL,
    SORT BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS `p_crm_field_multi` (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ENTITY VARCHAR(25) NOT NULL,
    ELEMENT_ID BIGINT NOT NULL,
    TYPE_ID VARCHAR(20) NOT NULL,
    VALUE_TYPE VARCHAR(30) NOT NULL,
    VALUE VARCHAR(255) NOT NULL
);